name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Generate Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          cd $GITHUB_WORKSPACE

          yarn run docs

          git clone "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" temp -b docs

          cd temp

          rm -rf collections/_classes/
          rm -rf collections/_interfaces/
          mv ../docs/README.md index.md
          mv ../docs/modules.md modules.md
          mv ../docs/classes collections/_classes/
          mv ../docs/interfaces collections/_interfaces/

          git add .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m "Built documentation for ${GITHUB_SHA}" || true
          git push origin docs
